clightning4j/ln-dashboard

- components/tableNodes/NodeTable.component.tsx
> Fixed mistake

- next.config.js
> make build consistent for all node versions

- next-env.d.ts
- package-lock.json
- package.json
> Migrate to new version of nextjs

- components/home/Home.component.tsx
Fixes https://github.com/clightning4j/ln-dashboard/issues/40
> Update QR with nodeId

- .gitignore
- api/AppAPI.ts
- api/JRestAPI.ts
- api/MockAPI.ts
- model/CoreLN.ts
- model/ListFunds.ts
This is enough to start implementing the real client and make this refractory?
What do you think?
> api: implementing the API client

- .gitignore
- pages/index.tsx
Super trivial, take me two secs :)
> fixed migration miu 5 with custom style

- components/appbar/BasicAppBar.component.jsx
- components/home/Home.component.tsx
- theme/DarkTheme.ts
> Remove override styles from theme

- pages/api/channelsInfo.ts
> Remove undefined channel in listNode 

- components/tableNodes/NodeTable.component.tsx
- model/CoreLN.ts
- utils/AppUtils.ts
Reverts Satoshi size to satoshi and removes msatoshi
> change msat to sat

- package-lock.json
- package.json
Changed versions of npm packages to fix the styling issue on the production
> fix production issue with change in npm packages

- components/home/Home.component.tsx
- package-lock.json
- package.json
> fix: update QRCode.react

- CHANGELOG.md
- changelog.json
- package-lock.json
- package.json
> prepare v0.0.3-beta.2

- CHANGELOG.md
- changelog.json
- package.json
> prepare v0.0.3-beta.3

- components/metricsView/cards/UpTimeNode.component.tsx
- package-lock.json
- package.json
- pages/_app.tsx
> fix: component is not a valid JSX element

- components/metricsView/cards/UpTimeNode.component.tsx
> feat: Add last update in the metrics view

- components/genericView/MetricsError.component.tsx
- pages/metrics.tsx
- utils/AppUtils.ts
> feat: Add metrics error page

- utils/AppUtils.ts
change `param instanceOf number` to `typeof param == "number"`
> fix: remove .inlcudes function

- CHANGELOG.md
- changelog.json
- package.json
> preapre v0.0.3-beta.4

- api/LNSocketAPI.ts
> fix: add no-cache policy

- CHANGELOG.md
- changelog.json
- package.json
> preapre release

- components/donation/DonationView.component.tsx
- components/home/Home.component.tsx
- components/notification/Notification.component.tsx
- components/tableNodes/NodeTable.component.tsx
- components/tableNodes/OfferTable.component.tsx
Fixes #60 
Added notification component to the app.
Future ref: There are four types of responses: `success, warning, error, info`
> feat: implement notification system

- CHANGELOG.md
- changelog.json
- package.json
> docs: release v0.0.3-beta.6

- api/LNSocketAPI.ts
> fix: catch the exception in the ping API

- components/notification/Notification.component.tsx
> fix: remove box shadow from the snackbar

- CHANGELOG.md
- changelog.json
- package.json
> docs: repapre release

- .github/workflows/release.yml
> feat: try to support multiple architecture with docker

- CHANGELOG.md
- api/LNSocketAPI.ts
- changelog.json
- components/tableNodes/OfferTable.component.tsx
- model/CoreLN.ts
- model/Offer.ts
- package-lock.json
> fix: fixes offers support
